[extend]
useDefault = true

[allowlist]
description = "Ignore unit and instrumentation test fixtures"
paths = [
    '''_test\.go$''',
    '''Test\.kt$''',
    '''src/test/''',
    '''src/androidTest/'''
]
