#!/usr/bin/env bash
# olcRTC server installer for systemd-based Linux VPS.
#
# Installs:
#   - /usr/local/bin/olcrtc                    statically-linked olcrtc binary
#   - /usr/local/bin/olcrtc-launcher           wrapper that translates env to flags
#   - /etc/systemd/system/olcrtc-server.service hardened systemd unit
#   - /etc/olcrtc/env                          OLCRTC_PROVIDER / ROOM_ID / KEY / DNS / DEBUG / SOCKS_PROXY
#   - /etc/olcrtc/key.hex                      32-byte encryption key (hex)
#
# Defaults: provider = wb_stream, room ID = auto-generated by Wildberries Stream
# at first start. The auto-generated room ID is captured from the live service
# logs and pinned into /etc/olcrtc/env so the same room is reused on restart.
#
# Idempotent. Re-run with --regenerate to get a fresh room ID; re-run with
# --regenerate-key to also rotate the encryption key.

set -euo pipefail

INSTALLER_VERSION="0.1.3"
PROVIDER_DEFAULT="jitsi"
DNS_DEFAULT="8.8.8.8:53"

REGENERATE_ROOM=0
REGENERATE_KEY=0
PROVIDER="${OLCRTC_PROVIDER:-$PROVIDER_DEFAULT}"
SET_SOCKS_PROXY="__keep__"     # "__keep__" = preserve existing setting in env file
SET_DEBUG="__keep__"           # "__keep__" = preserve existing setting in env file

usage() {
    cat <<EOF
Usage: sudo ./install.sh [options]

Options:
    --provider <jitsi|telemost|wbstream>
                          Pick a different provider (default: $PROVIDER_DEFAULT).
                          Can also be set via env: OLCRTC_PROVIDER.
    --regenerate          Drop the saved room ID and create a new one.
    --regenerate-key      Drop the encryption key AND room ID, regenerate both.
                          Existing clients will need the new key + room ID.
    --socks-proxy <[user:pass@]host:port>
                          Route the server's PROVIDER signalling (HTTP +
                          WebSocket) through a SOCKS5 proxy. Useful when the
                           VPS IP is blocked by wbstream / jitsi / telemost —
                          point this at a residential (e.g. RU) SOCKS5 proxy.
                          Both NO_AUTH and RFC 1929 USER/PASSWORD are
                          supported. Tunnelled client TCP traffic always
                          exits direct from the VPS, never via the proxy
                          (so geo-restricted services such as Telegram
                          remain reachable).
                          Forms accepted:
                            host:port                       (NO_AUTH)
                            user:pass@host:port             (RFC 1929)
                            socks5://[user:pass@]host:port  (same)
                          Pass "" to remove an existing setting.
    --debug               Enable verbose -debug logging in the systemd service
                          (helpful when diagnosing reconnects or DTLS issues).
    --no-debug            Disable verbose logging.
    -h, --help            Show this help.

Examples:
    sudo ./install.sh
    sudo ./install.sh --provider telemost --regenerate
    sudo ./install.sh --socks-proxy 1.2.3.4:1080
    sudo ./install.sh --socks-proxy alice:hunter2@1.2.3.4:1080
    sudo ./install.sh --debug
    sudo ./install.sh --socks-proxy ""        # remove proxy
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --provider) PROVIDER="$2"; shift 2 ;;
        --provider=*) PROVIDER="${1#*=}"; shift ;;
        --regenerate) REGENERATE_ROOM=1; shift ;;
        --regenerate-key) REGENERATE_KEY=1; REGENERATE_ROOM=1; shift ;;
        --socks-proxy) SET_SOCKS_PROXY="$2"; shift 2 ;;
        --socks-proxy=*) SET_SOCKS_PROXY="${1#*=}"; shift ;;
        --debug) SET_DEBUG="1"; shift ;;
        --no-debug) SET_DEBUG=""; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    esac
done

if [ "$(id -u)" -ne 0 ]; then
    echo "[!] This installer must be run as root (try: sudo $0 $*)" >&2
    exit 1
fi

case "$PROVIDER" in
    telemost|jitsi|jazz|wbstream|wb_stream) ;;
    *) echo "[!] Unsupported provider: $PROVIDER" >&2; exit 1 ;;
esac

if ! command -v systemctl >/dev/null 2>&1; then
    echo "[!] systemd is required but not found." >&2
    exit 1
fi

ARCH="$(uname -m)"
case "$ARCH" in
    x86_64|amd64)  BIN_NAME="olcrtc-linux-amd64" ;;
    aarch64|arm64) BIN_NAME="olcrtc-linux-arm64" ;;
    *)
        echo "[!] Unsupported CPU architecture: $ARCH" >&2
        echo "    Supported: x86_64 (amd64), aarch64 (arm64)." >&2
        exit 1
        ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_BIN="$SCRIPT_DIR/bin/$BIN_NAME"
SRC_UNIT="$SCRIPT_DIR/systemd/olcrtc-server.service"
SRC_LAUNCHER="$SCRIPT_DIR/systemd/olcrtc-launcher"

# When running from a clean checkout of master (which intentionally ships no
# pre-built binaries), download the matching binary from GitHub Releases.
# Tarball-based installs already include bin/$BIN_NAME, so this path is a no-op
# for them. The release tag tracks the installer version.
RELEASE_TAG="server-v$INSTALLER_VERSION"
RELEASE_URL_BASE="https://github.com/Oleglog/Olcrtc_manager/releases/download/$RELEASE_TAG"

if [ ! -f "$SRC_BIN" ]; then
    if ! command -v curl >/dev/null 2>&1; then
        echo "[!] Binary not bundled and curl is not installed. Install curl or download" >&2
        echo "    $BIN_NAME from $RELEASE_URL_BASE/$BIN_NAME and place it in $SCRIPT_DIR/bin/" >&2
        exit 1
    fi
    install -d -m 0755 "$SCRIPT_DIR/bin"
    echo "[*] Binary not bundled. Downloading $BIN_NAME from $RELEASE_TAG release..."
    if ! curl -fsSL "$RELEASE_URL_BASE/$BIN_NAME" -o "$SRC_BIN.tmp"; then
        echo "[!] Failed to download $BIN_NAME from $RELEASE_URL_BASE/" >&2
        echo "[!] Check that release '$RELEASE_TAG' exists, or build from source: see server-install/build-from-source.sh" >&2
        rm -f "$SRC_BIN.tmp"
        exit 1
    fi
    mv "$SRC_BIN.tmp" "$SRC_BIN"
    echo "[*] Downloaded to $SRC_BIN"
fi

if [ ! -x "$SRC_BIN" ]; then
    chmod +x "$SRC_BIN" 2>/dev/null || true
fi

if [ ! -f "$SRC_BIN" ]; then
    echo "[!] Missing binary: $SRC_BIN" >&2
    exit 1
fi
if [ ! -f "$SRC_UNIT" ]; then
    echo "[!] Missing systemd unit: $SRC_UNIT" >&2
    exit 1
fi
if [ ! -f "$SRC_LAUNCHER" ]; then
    echo "[!] Missing launcher script: $SRC_LAUNCHER" >&2
    exit 1
fi

CONFIG_DIR=/etc/olcrtc
STATE_DIR=/var/lib/olcrtc
ENV_FILE=$CONFIG_DIR/env
KEY_FILE=$CONFIG_DIR/key.hex

echo "[*] olcRTC server installer v$INSTALLER_VERSION"
echo "[*] Detected architecture: $ARCH ($BIN_NAME)"

if ! id olcrtc >/dev/null 2>&1; then
    echo "[*] Creating olcrtc system user..."
    useradd --system --no-create-home --shell /usr/sbin/nologin --home-dir "$STATE_DIR" olcrtc
fi

echo "[*] Installing binaries..."
install -m 0755 -o root -g root "$SRC_BIN" /usr/local/bin/olcrtc
install -m 0755 -o root -g root "$SRC_LAUNCHER" /usr/local/bin/olcrtc-launcher

echo "[*] Preparing $CONFIG_DIR and $STATE_DIR..."
install -d -m 0750 -o root -g olcrtc "$CONFIG_DIR"
install -d -m 0750 -o olcrtc -g olcrtc "$STATE_DIR"

# Generate or reuse the encryption key.
if [ "$REGENERATE_KEY" -eq 1 ] || [ ! -s "$KEY_FILE" ]; then
    echo "[*] Generating fresh 256-bit encryption key..."
    umask 077
    openssl rand -hex 32 > "$KEY_FILE"
    chown root:olcrtc "$KEY_FILE"
    chmod 0640 "$KEY_FILE"
fi
KEY="$(cat "$KEY_FILE")"

echo "[*] Installing systemd unit..."
install -m 0644 "$SRC_UNIT" /etc/systemd/system/olcrtc-server.service
systemctl daemon-reload

# --- Read previous env so we can preserve fields the user didn't touch. ---
EXISTING_ROOM=""
EXISTING_SOCKS_PROXY=""
EXISTING_DEBUG=""
if [ -f "$ENV_FILE" ]; then
    EXISTING_ROOM="$(grep -E '^OLCRTC_ROOM_ID=' "$ENV_FILE" | tail -1 | cut -d= -f2-)"
    EXISTING_SOCKS_PROXY="$(grep -E '^OLCRTC_SOCKS_PROXY=' "$ENV_FILE" | tail -1 | cut -d= -f2-)"
    EXISTING_DEBUG="$(grep -E '^OLCRTC_DEBUG=' "$ENV_FILE" | tail -1 | cut -d= -f2-)"
fi
if [ "$REGENERATE_ROOM" -eq 1 ]; then
    EXISTING_ROOM=""
fi

# Decide final SOCKS proxy / debug values.
if [ "$SET_SOCKS_PROXY" = "__keep__" ]; then
    SOCKS_PROXY="$EXISTING_SOCKS_PROXY"
else
    SOCKS_PROXY="$SET_SOCKS_PROXY"
fi
if [ "$SET_DEBUG" = "__keep__" ]; then
    DEBUG_FLAG="$EXISTING_DEBUG"
else
    DEBUG_FLAG="$SET_DEBUG"
fi

# Decide initial room ID. Use "any" for jitsi to trigger
# server-side auto-generation on first start.
if [ -n "$EXISTING_ROOM" ] && [ "$EXISTING_ROOM" != "any" ]; then
    ROOM_ID="$EXISTING_ROOM"
    echo "[*] Reusing existing room ID: $ROOM_ID"
elif [ "$PROVIDER" = "telemost" ]; then
    # Telemost requires a user-supplied room ID (any string works).
    ROOM_ID="${OLCRTC_ROOM_ID:-olcrtc-$(openssl rand -hex 4)}"
    echo "[*] Telemost room ID: $ROOM_ID"
else
    ROOM_ID="any"
fi

cat > "$ENV_FILE" <<EOF
# Managed by olcrtc install.sh — re-running the installer is safe.
OLCRTC_PROVIDER=$PROVIDER
OLCRTC_ROOM_ID=$ROOM_ID
OLCRTC_KEY=$KEY
OLCRTC_DNS=$DNS_DEFAULT
OLCRTC_DEBUG=$DEBUG_FLAG
OLCRTC_SOCKS_PROXY=$SOCKS_PROXY
EOF
chown root:olcrtc "$ENV_FILE"
chmod 0640 "$ENV_FILE"

echo "[*] Restarting olcrtc-server..."
systemctl enable --quiet olcrtc-server.service
systemctl restart olcrtc-server.service

# If we asked the provider to auto-create the room (id=any), capture the real
# room ID from the live journal and pin it. Skip for telemost (it uses the
# user-supplied ID directly).
if [ "$ROOM_ID" = "any" ]; then
    echo "[*] Waiting for $PROVIDER to create a room..."
    DETECTED=""
    PATTERN="(WB Stream room created|Jazz room created): "
    for i in $(seq 1 30); do
        sleep 1
        if DETECTED="$(journalctl -u olcrtc-server.service --since '1 minute ago' --no-pager 2>/dev/null \
            | grep -oE "$PATTERN\\S+" \
            | tail -1 \
            | awk '{print $NF}')"; then
            if [ -n "$DETECTED" ]; then
                ROOM_ID="$DETECTED"
                break
            fi
        fi
    done

    if [ -z "$DETECTED" ] || [ "$ROOM_ID" = "any" ]; then
        echo "[!] Failed to detect a generated room ID within 30s." >&2
        echo "[!] Last 30 log lines:" >&2
        journalctl -u olcrtc-server.service --no-pager -n 30 >&2 || true
        echo "[!] Service is still running (it may auto-recover); inspect logs and re-run with --regenerate." >&2
        exit 1
    fi

    sed -i -E "s|^OLCRTC_ROOM_ID=.*|OLCRTC_ROOM_ID=$ROOM_ID|" "$ENV_FILE"
    echo "[*] Pinned room ID and restarting service to reuse it across restarts..."
    systemctl restart olcrtc-server.service
    sleep 2
fi

PUBLIC_IP="$(curl -fsS --max-time 3 https://api.ipify.org 2>/dev/null || echo unknown)"

DEBUG_HUMAN="off"
if [ -n "$DEBUG_FLAG" ] && [ "$DEBUG_FLAG" != "0" ] && [ "$DEBUG_FLAG" != "false" ]; then
    DEBUG_HUMAN="on (-debug)"
fi

PROXY_HUMAN="(direct, no proxy)"
if [ -n "$SOCKS_PROXY" ]; then
    if [[ "$SOCKS_PROXY" == *"@"* ]]; then
        PROXY_HUMAN="${SOCKS_PROXY##*@} (SOCKS5 USER/PASSWORD, provider signalling only)"
    else
        PROXY_HUMAN="$SOCKS_PROXY (SOCKS5 NO_AUTH, provider signalling only)"
    fi
fi

cat <<EOF

==========================================================
        olcRTC server is up.
==========================================================

  Provider:        $PROVIDER
  Room ID:         $ROOM_ID
  Encryption key:  $KEY
  DNS resolver:    $DNS_DEFAULT
  Debug logging:   $DEBUG_HUMAN
  Outbound proxy:  $PROXY_HUMAN
  Public IP:       $PUBLIC_IP

  --- olcRTC Android profile fields ---
  Provider:        $PROVIDER
  Room ID:         $ROOM_ID
  Key (hex):       $KEY

  --- Manage the service ---
  Status:          systemctl status olcrtc-server
  Live logs:       journalctl -u olcrtc-server -f
  Restart:         systemctl restart olcrtc-server
  Stop:            systemctl stop olcrtc-server
  Edit env:        sudo \$EDITOR /etc/olcrtc/env  (then: systemctl restart olcrtc-server)
  Rotate room:     sudo $(realpath "$0") --regenerate
  Rotate key:      sudo $(realpath "$0") --regenerate-key
  Set proxy:       sudo $(realpath "$0") --socks-proxy host:port
  Remove proxy:    sudo $(realpath "$0") --socks-proxy ""
  Debug on/off:    sudo $(realpath "$0") --debug   |   --no-debug
==========================================================
EOF
